// POPUP
export const TOGGLE_SIMPLE_POPUP = 'TOGGLE_SIMPLE_POPUP'
export const TOGGLE_BASIC_POPUP = 'TOGGLE_BASIC_POPUP'

// VERIFY CODE
export const GET_VERIFY_CODE = 'GET_VERIFY_CODE'
export const RE_SEND_VERIFY_CODE  = 'RE_SEND_VERIFY_CODE'
export const RE_SEND_VERIFY_CODE_TIME  = 'RE_SEND_VERIFY_CODE_TIME'
export const CHECK_VERIFY_CODE = 'CHECK_VERIFY_CODE'

// USER CHECK IN BY localStorage
export const USER_CHECK_IN = 'USER_CHECK_IN'

// TOGGLE USER LOG/REGISTER POPUP
export const TOGGLE_USER_LOGIN_POPUP = 'TOGGLE_USER_LOGIN_POPUP'
export const TOGGLE_USER_REGISTER_POPUP = 'TOGGLE_USER_REGISTER_POPUP'

// USER REGISTER
export const USER_REGISTER_ACTION = 'USER_REGISTER_ACTION'
export const USER_REGISTER_INFO = 'USER_REGISTER_INFO'
export const USER_REGISTER_ERRORS = 'USER_REGISTER_ERRORS'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'

// USER SIGN IN/OUT SECTION
export const USER_SIGN_IN_ACTION = 'USER_SIGN_IN_ACTION'
export const USER_SIGN_IN_INFO = 'USER_SIGN_IN_INFO'
export const USER_SIGN_IN_ERRORS = 'USER_SIGN_IN_ERRORS'
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS'
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILURE'
export const USER_SIGN_OUT = 'USER_SIGN_OUT'

// MODIFY USER SECTION
export const USER_MODIFY_INFO_ACTION = 'USER_MODIFY_INFO_ACTION'
export const USER_MODIFY_INFO_PROCESSING = 'USER_MODIFY_INFO_PROCESSING'
export const USER_MODIFY_INFO_ERRORS = 'USER_MODIFY_INFO_ERRORS'
export const USER_MODIFY_INFO_SUCCESS = 'USER_MODIFY_INFO_SUCCESS'
export const USER_MODIFY_INFO_FAILURE = 'USER_MODIFY_INFO_FAILURE'

// MODIFY PASSWORD SECTION
export const USER_MODIFY_PASSWORD_ACTION = 'USER_MODIFY_PASSWORD_ACTION'
export const USER_MODIFY_PASSWORD_INFO = 'USER_MODIFY_PASSWORD_INFO'
export const USER_MODIFY_PASSWORD_ERRORS = 'USER_MODIFY_PASSWORD_ERRORS'
export const USER_MODIFY_PASSWORD_SUCCESS = 'USER_MODIFY_PASSWORD_SUCCESS'
export const USER_MODIFY_PASSWORD_FAILURE = 'USER_MODIFY_PASSWORD_FAILURE'

// PRIMARY NAV
export const PRIMARY_NAV_UPDATE = 'PRIMARY_NAV_UPDATE'

// BABY LIST SECTION
export const CHILD_LIST = 'CHILD_LIST'
export const CHILD_GET_ALL = 'CHILD_GET_ALL'
export const CHILD_DETAIL = 'CHILD_DETAIL'
export const CHILD_RECEIVED = 'CHILD_RECEIVED'

// BABY ADD SECTION
export const CHILD_ADD_ACTION = 'CHILD_ADD_ACTION'
export const CHILD_ADD_ERRORS = 'CHILD_ADD_ERRORS'
export const CHILD_ADD_SUCCESS = 'CHILD_ADD_SUCCESS'
export const CHILD_ADD_FAILURE = 'CHILD_ADD_FAILURE'

// BABY REMOVE SECTION
export const CHILD_REMOVE_ACTION = 'CHILD_REMOVE_ACTION'
export const CHILD_REMOVE_ERRORS = 'CHILD_REMOVE_ERRORS'
export const CHILD_REMOVE_SUCCESS = 'CHILD_REMOVE_SUCCESS'
export const CHILD_REMOVE_FAILURE = 'CHILD_REMOVE_FAILURE'

// BABY DETAIL MODIFY SECTION
export const CHILD_DETAIL_MODIFY_ACTION = 'CHILD_DETAIL_MODIFY_ACTION'
export const CHILD_DETAIL_MODIFY_ERRORS = 'CHILD_DETAIL_MODIFY_ERRORS'
export const CHILD_DETAIL_MODIFY_SUCCESS = 'CHILD_DETAIL_MODIFY_SUCCESS'
export const CHILD_DETAIL_MODIFY_FAILURE = 'CHILD_DETAIL_MODIFY_FAILURE'
