// USER CHECK IN BY localStorage
export const USER_CHECK_IN = 'USER_CHECK_IN'

// TOGGLE USER LOG/REGISTER POPUP
export const TOGGLE_USER_LOGIN_POPUP = 'TOGGLE_USER_LOGIN_POPUP'
export const TOGGLE_USER_REGISTER_POPUP = 'TOGGLE_USER_REGISTER_POPUP'


// USER SIGN IN/OUT SECTION
export const USER_SIGN_IN_ACTION = 'USER_SIGN_IN_ACTION'
export const USER_SIGN_IN_INFO = 'USER_SIGN_IN_INFO'
export const USER_SIGN_IN_ERRORS = 'USER_SIGN_IN_ERRORS'
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS'
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILURE'
export const USER_SIGN_OUT = 'USER_SIGN_OUT'

// VERIFY CODE SECTION
// export const SEND_VERIFY_CODE = 'SEND_VERIFY_CODE'

// MODIFY USER SECTION
export const MODIFY_USER_INFO_START = 'MODIFY_USER_INFO_START'
export const MODIFY_USER_INFO_PROCESSING = 'MODIFY_USER_INFO_PROCESSING'
export const MODIFY_USER_INFO_SUCCESS = 'MODIFY_USER_INFO_SUCCESS'
export const MODIFY_USER_INFO_FAILURE = 'MODIFY_USER_INFO_FAILURE'

// PRIMARY NAV
export const PRIMARY_NAV_UPDATE = 'PRIMARY_NAV_UPDATE'
