
// UER SIGN IN/OUT SECTION
export const USER_SIGN_IN = 'USER_SIGN_IN'
export const USER_SIGN_IN_INFO = 'USER_SIGN_IN_INFO'
export const USER_SIGN_IN_ERRORS = 'USER_SIGN_IN_ERRORS'
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS'
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILURE'
export const USER_SIGN_OUT = 'USER_SIGN_OUT'

// VERIFY CODE SECTION
export const GET_VERIFY_CODE = 'GET_VERIFY_CODE'
export const VERIFY_CODE_REMAIN = 'VERIFY_CODE_REMAIN'

// MODIFY USER SECTION
export const MODIFY_USER_INFO_START = 'MODIFY_USER_INFO_START'
export const MODIFY_USER_INFO_PROCESSING = 'MODIFY_USER_INFO_PROCESSING'
export const MODIFY_USER_INFO_SUCCESS = 'MODIFY_USER_INFO_SUCCESS'
export const MODIFY_USER_INFO_FAILURE = 'MODIFY_USER_INFO_FAILURE'

// PRIMARY NAV
export const PRIMARY_NAV_UPDATE = 'PRIMARY_NAV_UPDATE'
